/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raveen
 */
public class attendence extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public attendence() {
        initComponents();
        setIconImage();
        Connect();
        
    }
    
    
    private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;
    
    public void Connect()
    {   
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/2checkdb", "root", "");
            
            
        } 
        catch (ClassNotFoundException ex) {
            Logger.getLogger(CrudForAdminOnG.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CrudForAdminOnG.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        attendence = new javax.swing.JButton();
        examresults = new javax.swing.JButton();
        timetable = new javax.swing.JButton();
        paymentdetails = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        displayAlert = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        atDateandTime = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Module2 = new javax.swing.JLabel();
        Module4 = new javax.swing.JLabel();
        mdCode1 = new javax.swing.JTextField();
        stID1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Module = new javax.swing.JLabel();
        Module1 = new javax.swing.JLabel();
        mdCode = new javax.swing.JTextField();
        stID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        attendence.setBackground(new java.awt.Color(0, 7, 152));
        attendence.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/creation/attendenceclick.png"))); // NOI18N
        attendence.setBorder(null);
        attendence.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attendence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendenceActionPerformed(evt);
            }
        });
        getContentPane().add(attendence, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 341, 42));

        examresults.setBackground(new java.awt.Color(0, 7, 152));
        examresults.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/creation/exam results.jpg"))); // NOI18N
        examresults.setBorder(null);
        examresults.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        examresults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examresultsActionPerformed(evt);
            }
        });
        getContentPane().add(examresults, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 341, 42));

        timetable.setBackground(new java.awt.Color(0, 7, 152));
        timetable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/creation/time table.jpg"))); // NOI18N
        timetable.setBorder(null);
        timetable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timetableActionPerformed(evt);
            }
        });
        getContentPane().add(timetable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 341, 42));

        paymentdetails.setBackground(new java.awt.Color(0, 7, 152));
        paymentdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/creation/paymebt details.jpg"))); // NOI18N
        paymentdetails.setBorder(null);
        paymentdetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paymentdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentdetailsActionPerformed(evt);
            }
        });
        getContentPane().add(paymentdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 341, 42));

        logout.setBackground(new java.awt.Color(0, 7, 152));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/creation/logout.jpg"))); // NOI18N
        logout.setBorder(null);
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 341, 42));

        displayAlert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(displayAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 220, 20));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/creation/normalhome.png"))); // NOI18N
        home.setBorder(null);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 341, 42));

        atDateandTime.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Attendance marked Date & Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(atDateandTime);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 220, 210));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/buttons/View.jpg"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 190, 32));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("View your attendence");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 170, 20));

        Module2.setBackground(new java.awt.Color(204, 204, 204));
        Module2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        Module2.setForeground(new java.awt.Color(0, 0, 0));
        Module2.setText("Module Code");
        jPanel4.add(Module2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 20));

        Module4.setBackground(new java.awt.Color(204, 204, 204));
        Module4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        Module4.setForeground(new java.awt.Color(0, 0, 0));
        Module4.setText("Student ID");
        jPanel4.add(Module4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 20));

        mdCode1.setBackground(new java.awt.Color(255, 255, 255));
        mdCode1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mdCode1.setBorder(null);
        jPanel4.add(mdCode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 110, 20));

        stID1.setBackground(new java.awt.Color(255, 255, 255));
        stID1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stID1.setBorder(null);
        jPanel4.add(stID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 110, 20));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 220, 200));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitButton.setBackground(new java.awt.Color(0, 7, 152));
        submitButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        submitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/buttons/submit blue.jpg"))); // NOI18N
        submitButton.setBorder(null);
        submitButton.setBorderPainted(false);
        submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 190, 32));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Mark your attendence");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 170, 20));

        Module.setBackground(new java.awt.Color(204, 204, 204));
        Module.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        Module.setForeground(new java.awt.Color(0, 0, 0));
        Module.setText("Module Code");
        jPanel1.add(Module, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 20));

        Module1.setBackground(new java.awt.Color(204, 204, 204));
        Module1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        Module1.setForeground(new java.awt.Color(0, 0, 0));
        Module1.setText("Student ID");
        jPanel1.add(Module1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 20));

        mdCode.setBackground(new java.awt.Color(255, 255, 255));
        mdCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mdCode.setBorder(null);
        jPanel1.add(mdCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 110, 20));

        stID.setBackground(new java.awt.Color(255, 255, 255));
        stID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stID.setBorder(null);
        jPanel1.add(stID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 110, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 220, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/creation/new new desighn.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
home home1 = new home();
       home1.setVisible(true);
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void attendenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendenceActionPerformed
attendence attendence1 = new attendence();
       attendence1.setVisible(true);
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_attendenceActionPerformed

    private void timetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timetableActionPerformed
timetable timetable1 = new timetable();
       timetable1.setVisible(true);
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_timetableActionPerformed

    private void examresultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examresultsActionPerformed
examresults examresults1 = new examresults();
       examresults1.setVisible(true);
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_examresultsActionPerformed

    private void paymentdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentdetailsActionPerformed
paymentdetails paymentdetails1 = new paymentdetails();
       paymentdetails1.setVisible(true);
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_paymentdetailsActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
login frame1 = new login();
        frame1.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        
        if(mdCode.getText().trim().isEmpty() && stID.getText().trim().isEmpty())
        {
            displayAlert.setText("Module code and Student id is empty!");
        }
        
        else if(mdCode.getText().trim().isEmpty())
        {
            displayAlert.setText("Module code cannot be empty");
        }
        
        else if(stID.getText().trim().isEmpty())
        {
            displayAlert.setText("Student-Id cannot be empty!");
        }
        else
        {
            displayAlert.setText("");
        }
       
       
        try {
            
            String myModule = mdCode.getText();
            String myId = stID.getText();
            
            pst = (PreparedStatement) con.prepareStatement("INSERT INTO attendance(modulecode,studentid) VALUES(?,?)");
            pst.setString(1, myModule);
            pst.setString(2, myId);
            
             int updt = pst.executeUpdate();
            
            if(updt == 1)
            {
                JOptionPane.showMessageDialog(this,"Attendance marked.");
                mdCode.setText("");
                stID.setText("");
                mdCode.requestFocus();
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Failed to mark attendance.");
            }
            
        } 
        catch (SQLException ex) {
            Logger.getLogger(attendence.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        LoadAttendance();
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    void LoadAttendance()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/2checkdb", "root", "");
         
            pst = (PreparedStatement) con.prepareStatement("SELECT time FROM attendance WHERE modulecode=? AND studentid=?");
            pst.setString(1, mdCode1.getText());
            pst.setString(2, stID1.getText());
            ResultSet rs = pst.executeQuery();
            while(atDateandTime.getRowCount()>0)
            {
                ((DefaultTableModel)atDateandTime.getModel()).removeRow(0);
            }
            
            int col = rs.getMetaData().getColumnCount();
            while(rs.next())
            {
              Object [] rows = new Object[col];
              for(int i=1;i<=col;i++)
              {
                  rows[i-1] = rs.getObject(i);
              }
              ((DefaultTableModel)atDateandTime.getModel()).insertRow(rs.getRow() -1, rows);
            
            }
            rs.close();
            pst.close();
           
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CrudForAdminOnG.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CrudForAdminOnG.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
        
    }
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new attendence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Module;
    private javax.swing.JLabel Module1;
    private javax.swing.JLabel Module2;
    private javax.swing.JLabel Module4;
    private javax.swing.JTable atDateandTime;
    private javax.swing.JButton attendence;
    private javax.swing.JLabel displayAlert;
    private javax.swing.JButton examresults;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JTextField mdCode;
    private javax.swing.JTextField mdCode1;
    private javax.swing.JButton paymentdetails;
    private javax.swing.JTextField stID;
    private javax.swing.JTextField stID1;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton timetable;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
