/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Raveen
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginusername = new javax.swing.JTextField();
        loginpassword = new javax.swing.JPasswordField();
        displayAlert = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginusername.setBackground(new java.awt.Color(255, 255, 255));
        loginusername.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        loginusername.setForeground(new java.awt.Color(153, 153, 153));
        loginusername.setText("Student ID No.");
        loginusername.setToolTipText("Enter Your Username");
        loginusername.setBorder(null);
        loginusername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        loginusername.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        loginusername.setDoubleBuffered(true);
        loginusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                loginusernameKeyTyped(evt);
            }
        });
        getContentPane().add(loginusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 140, 20));

        loginpassword.setBackground(new java.awt.Color(255, 255, 255));
        loginpassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        loginpassword.setForeground(new java.awt.Color(153, 153, 153));
        loginpassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        loginpassword.setText("dfdfdfdf");
        loginpassword.setToolTipText("Enter Your Password");
        loginpassword.setAutoscrolls(false);
        loginpassword.setBorder(null);
        loginpassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(loginpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 355, 140, 20));

        displayAlert.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 10)); // NOI18N
        displayAlert.setForeground(new java.awt.Color(245, 49, 49));
        displayAlert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displayAlert.setToolTipText("");
        getContentPane().add(displayAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 270, 20));

        jButton2.setBackground(new java.awt.Color(163, 248, 66));
        jButton2.setForeground(new java.awt.Color(73, 75, 71));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/buttons/LAA.jpg"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 120, 28));

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/creation/login2.png"))); // NOI18N
        login.setBorder(null);
        login.setBorderPainted(false);
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 120, 28));

        jLabel1.setForeground(new java.awt.Color(51, 51, 55));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/creation/loginback.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginusernameKeyTyped
       
    }//GEN-LAST:event_loginusernameKeyTyped

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

        if(loginusername.getText().trim().isEmpty() && loginpassword.getText().trim().isEmpty())
        {
            displayAlert.setText("Username and password is empty!");
        }
        
        else if(loginusername.getText().trim().isEmpty())
        {
            displayAlert.setText("Username cannot be empty!");
        }
        
        else if(loginpassword.getText().trim().isEmpty())
        {
            displayAlert.setText("Password cannot be empty!");
        }
        else
        {
            displayAlert.setText("");
        }
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/2checkdb", "root", "");
            String sql = "SELECT * FROM logme WHERE studentid=? AND password=?";
            PreparedStatement pst = (PreparedStatement) con.prepareStatement(sql);
            pst.setString(1, loginusername.getText());
            pst.setString(2, loginpassword.getText());
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next())
            {
                JOptionPane.showMessageDialog(null, "Welcome to 2Check NSBM");
                home home1 = new home();
                home1.setVisible(true);
                setVisible(false);
            }
            
            else
            {
                JOptionPane.showMessageDialog(null, "Invalid Username or password");
                loginusername.setText("");
                loginpassword.setText("");
            }
            
            con.close();
            
             
            
            
            //
            //
            //       
        } 
        catch (ClassNotFoundException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Adminog loginForm = new Adminog();
                loginForm.setVisible(true);
                setVisible(false);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel displayAlert;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField loginpassword;
    private javax.swing.JTextField loginusername;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
