/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf;

import code.DBconect;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Raveen
 */
public class timetable extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement psd = null;
    ResultSet rs = null;

    /**
     * Creates new form home
     */
    public timetable() {
        initComponents();
        setIconImage();
        conn = DBconect.connect();
        
        
    }
    public void tableload(){
        String date1;
        date1 = datebox.getText();
        
        try {
            String sql = "SELECT time,module,lecturere FROM timetable2 WHERE date='"+date1+"'";
            psd = conn.prepareStatement(sql);
            rs = psd.executeQuery();
            ttable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        attendence = new javax.swing.JButton();
        examresults = new javax.swing.JButton();
        timetable = new javax.swing.JButton();
        paymentdetails = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        view = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        datebox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ttable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        attendence.setBackground(new java.awt.Color(0, 7, 152));
        attendence.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/creation/attendence.jpg"))); // NOI18N
        attendence.setBorder(null);
        attendence.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attendence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendenceActionPerformed(evt);
            }
        });
        getContentPane().add(attendence, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 341, 42));

        examresults.setBackground(new java.awt.Color(0, 7, 152));
        examresults.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/creation/exam results.jpg"))); // NOI18N
        examresults.setBorder(null);
        examresults.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        examresults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examresultsActionPerformed(evt);
            }
        });
        getContentPane().add(examresults, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 341, 42));

        timetable.setBackground(new java.awt.Color(0, 7, 152));
        timetable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/creation/timtableclick.png"))); // NOI18N
        timetable.setBorder(null);
        timetable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timetableActionPerformed(evt);
            }
        });
        getContentPane().add(timetable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 341, 42));

        paymentdetails.setBackground(new java.awt.Color(0, 7, 152));
        paymentdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/creation/paymebt details.jpg"))); // NOI18N
        paymentdetails.setBorder(null);
        paymentdetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paymentdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentdetailsActionPerformed(evt);
            }
        });
        getContentPane().add(paymentdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 341, 42));

        logout.setBackground(new java.awt.Color(0, 7, 152));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/creation/logout.jpg"))); // NOI18N
        logout.setBorder(null);
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 341, 42));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/creation/normalhome.png"))); // NOI18N
        home.setBorder(null);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 341, 42));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        view.setBackground(new java.awt.Color(0, 7, 152));
        view.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/buttons/view time table 2.jpg"))); // NOI18N
        view.setBorder(null);
        view.setBorderPainted(false);
        view.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jPanel1.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 190, 32));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("time table");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, 20));

        datebox.setBackground(new java.awt.Color(204, 204, 204));
        datebox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        datebox.setForeground(new java.awt.Color(51, 51, 51));
        datebox.setText("YYYY/MM/DD");
        datebox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(datebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 110, -1));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 40, 40));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Enter the date specifically");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 20));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("that you want to see the ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 170, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 190, 160));

        ttable.setBackground(new java.awt.Color(204, 204, 204));
        ttable.setForeground(new java.awt.Color(0, 0, 0));
        ttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "time", "Module name", "lecturere name"
            }
        ));
        ttable.setFillsViewportHeight(true);
        ttable.setRowHeight(20);
        ttable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        ttable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(ttable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 350, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/creation/new new desighn.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
home home1 = new home();
       home1.setVisible(true);
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void attendenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendenceActionPerformed
attendence attendence1 = new attendence();
       attendence1.setVisible(true);
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_attendenceActionPerformed

    private void timetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timetableActionPerformed
timetable timetable1 = new timetable();
       timetable1.setVisible(true);
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_timetableActionPerformed

    private void examresultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examresultsActionPerformed
examresults examresults1 = new examresults();
       examresults1.setVisible(true);
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_examresultsActionPerformed

    private void paymentdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentdetailsActionPerformed
paymentdetails paymentdetails1 = new paymentdetails();
       paymentdetails1.setVisible(true);
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_paymentdetailsActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
login frame1 = new login();
        frame1.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
       
        tableload();
    }//GEN-LAST:event_viewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new timetable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attendence;
    private javax.swing.JTextField datebox;
    private javax.swing.JButton examresults;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JButton paymentdetails;
    private javax.swing.JButton timetable;
    private javax.swing.JTable ttable;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
